### ISSUE TITLE
struggling to install power1d

### ISSUE THREAD

**Issue by Little-Foot-Shapes** [0todd0000/power1d#1]
Hello, 

I am new to Python. Managed to download and work it in vscode, but I am not able to install power1d. I installed spm1d, but 
it gives me this error when I try to install power1d using either of the below methods:

PS F:\> py -m easy_install power1d
WARNING: The easy_install command is deprecated and will be removed in a future version.
Processing power1d
error: Couldn't find a setup script in F:\power1d

PS F:\> py -m pip install power1d
ERROR: Could not find a version that satisfies the requirement power1d
ERROR: No matching distribution found for power1d

Your help would be much appreciated.

Thank you.
Mat

**Comment by 0todd0000** [comment]
Hi, power1d is not hosted on PyPI (pypi.org) so easy_install and pip will not work. To install packages with setup.py files, first download the source code, navigate into the folder containing setup.py, then enter this command:

`python setup.py install`

This will install the package in your default Python distribution. To find out where it installed, launch Python by entering `python` in a Terminal or Command Prompt, then enter:

```python
>>> import power1d
>>> print( power1d )
```

In my case the files are installed to the following folder:
/opt/anaconda3/lib/python3.8/site-package/power1d-0.1.1-py3.8.egg

To uninstall the package simply delete this folder.

**Comment by Little-Foot-Shapes** [comment]
Thank you it worked!
