### ISSUE TITLE
Repeated Measures ANOVA

### ISSUE THREAD

**Issue by jouterleys** [0todd0000/power1d#6]
Hi Todd,

I'm wondering if there are additional considerations for extending the [One-way ANOVA Example](https://spm1d.org/power1d/Examples/PowerAnalysis.html#one-way-anova) for repeated measures? 

Best,
Jereme

**Comment by 0todd0000** [comment]
Good point!  As you note this functionality does not exist yet, but it certainly should exist for completion. One reason it does not yet exist is that the sister package **spm1d** does not yet support all repeated-measures complexities like non-sphericity. Those complexities should be solved in the next major version of **spm1d** so at that point I agree that it would be good to support RM designs in **power1d** too. In the meantime, please find that I've started a new thread here: #7 for feature requests and added RM designs at the top.

**Comment by jouterleys** [comment]
Thanks Todd - both will be great additions.

I have another question about the [random effects analysis using hierarchical models](https://spm1d.org/doc/RandomEffects.html#overview-of-random-effects-analysis) in **spm1d**. But I'll close this issue.

**Comment by jouterleys** [comment]
Moved to [#7](https://github.com/0todd0000/power1d/issues/7) as feature request.
