### ISSUE TITLE
Hierarchical (two-level) Random Effects Model

### ISSUE THREAD

**Issue by jouterleys** [0todd0000/power1d#8]
Hi Todd,

I'm trying to determine the steps when using power1d for a hierarchical (two-level) random effects model as outlined [here](https://spm1d.org/doc/RandomEffects.html) in **spm1d**.

I'm assuming the actual analysis is based on simulating the beta continuum estimates and then running stats.t_1sample( ).

Would the steps here be to create data sample models for the regression, generate the beta coefficients (perhaps with spm1d) and using those in creating the experimental models?

If you had an example matching the data for **spm1d** I think that would be helpful.

Thanks!

**Comment by 0todd0000** [comment]
> I'm assuming the actual analysis is based on simulating the beta continuum estimates and then running stats.t_1sample( )

That is correct, you need a hypothesized `beta`.

<br>
<br>

> Would the steps here be to create data sample models for the regression, generate the beta coefficients (perhaps with spm1d) and using those in creating the experimental models?

I suggest going straight to the hypothesized `beta`. A random effects model like this tests the null hypothesis that `beta` is zero. For power analysis you simply need to define the hypothesized, true `beta` effect that would cause you to reject the null hypothesis of "no effect".

*Note*: from the perspective of power analysis, this two-level approach is actually exactly the same as a standard (one-level) t-test. The only difference is the interpretation of the modeled data. For a standard t-test the modeled data represent actual measurements. For a two-level test the modeled data represent `beta` effects.

**Comment by jouterleys** [comment]
Awesome thanks Todd.

**Comment by jouterleys** [comment]
Awesome thanks Todd!
